version: '3'
services:
    xray:
        image: v2fly/v2fly-core
        hostname: 'xray'
        container_name: xray
        restart: always
        command: run -c /etc/v2ray/config.json
        ports:
            - 443:443
            - 80:80
        volumes:
            - ./config.json:/etc/v2ray/config.json
